config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :fileuploads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: 'pages#_'
  post "/ingestSale", to: "sales#ingest"
  root to: "pages#_"
  get "/totalRevenue", to: 'sales#total_revenue'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fileupload.rb
class Fileupload < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fileuploads_controller.rb
class FileuploadsController < ApplicationController
  before_action :set_fileupload, only: [:show, :edit, :update, :destroy]

  # GET /fileuploads
  # GET /fileuploads.json
  def index
    @fileuploads = Fileupload.all
  end

  # GET /fileuploads/1
  # GET /fileuploads/1.json
  def show
  end

  # GET /fileuploads/new
  def new
    @fileupload = Fileupload.new
  end

  # GET /fileuploads/1/edit
  def edit
  end

  # POST /fileuploads
  # POST /fileuploads.json
  def create
    @fileupload = Fileupload.new(fileupload_params)

    respond_to do |format|
      if @fileupload.save
        format.html { redirect_to @fileupload, notice: 'Fileupload was successfully created.' }
        format.json { render :show, status: :created, location: @fileupload }
      else
        format.html { render :new }
        format.json { render json: @fileupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fileuploads/1
  # PATCH/PUT /fileuploads/1.json
  def update
    respond_to do |format|
      if @fileupload.update(fileupload_params)
        format.html { redirect_to @fileupload, notice: 'Fileupload was successfully updated.' }
        format.json { render :show, status: :ok, location: @fileupload }
      else
        format.html { render :edit }
        format.json { render json: @fileupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fileuploads/1
  # DELETE /fileuploads/1.json
  def destroy
    @fileupload.destroy
    respond_to do |format|
      format.html { redirect_to fileuploads_url, notice: 'Fileupload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fileupload
      @fileupload = Fileupload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fileupload_params
      params.require(:fileupload).permit(:fname, :content_type, :contents)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  protect_from_forgery with: :null_session

  def ingest
    model_mapping = {
      "Customer Name" => :customer_name,
      "Item Description" => :item_description,
      "Item Price" => :item_price,
      "Quantity" => :quantity,
      "Merchant Name" => :merchant_name,
      "Merchant Address\r" => :merchant_address
    }

    headings = params["data"]["headings"]
    sale_obj = {}
    sale_hash = ''
    params["data"].each { |item, val|
      if item != "headings"
        if (model_mapping[item] == :item_price) || (model_mapping[item] == :quantity)
          sale_obj[model_mapping[item]] = val.to_f
        else
          sale_obj[model_mapping[item]] = val.strip
        end
      end
    }
    puts Sale.create(sale_obj)
  end

  def total_revenue
    @totalRevenue = 0
    Sale.all.each {|sale|
      @totalRevenue += sale.item_price*sale.quantity
    }
    render "sales/total_revenue"
  end

private
  def sales_params
    params.require(:sale).permit(Sale.column_names)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fileuploads_helper.rb
module FileuploadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/fileuploads/_form.html.erb
<%= form_with(model: fileupload, local: true) do |form| %>
  <% if fileupload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fileupload.errors.count, "error") %> prohibited this fileupload from being saved:</h2>

      <ul>
      <% fileupload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :content_type %>
    <%= form.text_field :content_type %>
  </div>

  <div class="field">
    <%= form.label :contents %>
    <%= form.text_field :contents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fileuploads/edit.html.erb
<h1>Editing Fileupload</h1>

<%= render 'form', fileupload: @fileupload %>

<%= link_to 'Show', @fileupload %> |
<%= link_to 'Back', fileuploads_path %>

app/views/fileuploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fileuploads</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Content type</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fileuploads.each do |fileupload| %>
      <tr>
        <td><%= fileupload.fname %></td>
        <td><%= fileupload.content_type %></td>
        <td><%= fileupload.contents %></td>
        <td><%= link_to 'Show', fileupload %></td>
        <td><%= link_to 'Edit', edit_fileupload_path(fileupload) %></td>
        <td><%= link_to 'Destroy', fileupload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fileupload', new_fileupload_path %>

app/views/fileuploads/new.html.erb
<h1>New Fileupload</h1>

<%= render 'form', fileupload: @fileupload %>

<%= link_to 'Back', fileuploads_path %>

app/views/fileuploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @fileupload.fname %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @fileupload.content_type %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @fileupload.contents %>
</p>

<%= link_to 'Edit', edit_fileupload_path(@fileupload) %> |
<%= link_to 'Back', fileuploads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<div class="container">
  hello


</div>

app/views/pages/_.html.erb
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<div class="container">
  <h1 style="text-align: center">Sales Admin</h1>

  <div id="dvImportSegments" class="fileupload ">
      <fieldset>
          <legend>Upload .csv file with sales data</legend>
              <input type="file" name="File Upload" id="csvFileUpload" accept=".csv" />
     </fieldset>
  </div>


  <div class="subcontainer"></div>
  <div class="revenueLink"></div>
</div>



<script type="text/javascript">
var csrfToken = $("meta[name='csrf-token']").attr("content");

// Method that checks that the browser supports the HTML5 File API
function compatibleBrowser() {
    var isCompatible = false;
    if (window.File && window.FileReader && window.FileList && window.Blob) {
      isCompatible = true;
    }
    return isCompatible;
}

// Method that reads and processes the selected file
function upload(event){
  if (!compatibleBrowser()) {
    alert('File APIs (HTML5) are not available with this browser!');
  } else {
    var data = null;
    var file = event.target.files[0];
    var reader = new FileReader();
    reader.readAsText(file);
    totalRevenue = 0;
    reader.onload = function(event) {
        var csvData = event.target.result;
        let lines = csvData.split("\n");
        var row = 0;
        var headers = null;
        var headerIndex = 0
        var priceIndex = 0;
        var quantityIndex = 0;
        var sales = []
        lines.forEach(function(line) {
          var elts = line.split(",");
          if(row === 0) { // header row
            headers = elts;
            headers.forEach(function(header){
              if (header === "Item Price") { priceIndex = headerIndex; }
              if (header === "Quantity") { quantityIndex = headerIndex; }
              headerIndex += 1;
            })
          }
          else {
            var obj = {};
            var eltIndex = 0;
            elts.forEach(function(elt){
              if (eltIndex === priceIndex || eltIndex === quantityIndex) {
                obj[headers[eltIndex]] = parseFloat(elt);
              }
              else {
                obj[headers[eltIndex]] = elt;
              }
              eltIndex += 1;
            });
            obj['headings'] = headers;
            console.log(obj);
            sales.push(obj);
            totalRevenue += parseFloat(elts[priceIndex])*parseFloat(elts[quantityIndex]);
          }
          row += 1;
        });

        $('.subcontainer').html('</br>Total revenue in uploaded .csv: $'+totalRevenue);

        sales.forEach(function(sale){
          const url = "localhost:3535/ingestSale";
          console.log(csrfToken);
          $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                  if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                      xhr.setRequestHeader("X-CSRF-Token", csrfToken)
                  }
              }
          });
          $.ajax({
            url: url,
            data: {"data": sale},
            type: 'POST'
          }).done(function(data){
            console.log(`${data}`);
          });
        });

      $('.revenueLink').html('<a href="/totalRevenue">View Total Revenue</a>')
    };
    reader.onerror = function() {
        alert('Unable to read ' + file.fileName);
    };
  }
}

$(document).ready(function() {
  // The event listener for the file upload
  document.getElementById('csvFileUpload').addEventListener('change', upload, false);
});




</script>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/sales/total_revenue.html.erb
<h1> Total Revenue </h1>

<% if @totalRevenue %>
<p><%= @totalRevenue %></p>
<% end %>